# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: acc-{{ .Values.bank.account }}-config
data:
  account_no: "{{ .Values.bank.account | b64enc }}"
  bank: {{ .Values.bank.bank | b64enc }}
  device_id: {{ .Values.bank.device_id | b64enc }}
  pincode: {{ .Values.bank.pincode | b64enc }}