apiVersion: v1
kind: Service
metadata:
  name: nodeport-acc-{{ .Values.bank.account }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    app: acc-{{ .Values.bank.account }}
